-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 00:24:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportcode_
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sportcode_` ;

-- -----------------------------------------------------
-- Schema sportcode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportcode_` DEFAULT CHARACTER SET utf8 ;
USE `sportcode_` ;

-- -----------------------------------------------------
-- Table `sportcode`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primero_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primero_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Administrador` (
  `numero_cc` INT NOT NULL,
  `biografia` LONGTEXT NOT NULL,
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`numero_cc`),
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mysportcodedb`.`entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`entrenador` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`entrenador` (
  `numero_cc` INT NOT NULL,
  `biografia` TEXT NOT NULL,
  `experiencia` TEXT NOT NULL,
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`numero_cc`),
  INDEX `fk_entrenador_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_entrenador_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`rutinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`rutinas` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`rutinas` (
  `numero_de_clase` TINYINT NOT NULL,
  `velocidad` VARCHAR(45) NULL,
  `resistencia` VARCHAR(45) NULL,
  `fuerza` VARCHAR(45) NULL,
  `coordinacion` VARCHAR(45) NULL,
  `entrenador_numero_cc` INT NOT NULL,
  PRIMARY KEY (`numero_de_clase`),
  INDEX `fk_rutinas_entrenador1_idx` (`entrenador_numero_cc` ASC)  ,
  UNIQUE INDEX `entrenador_numero_cc_UNIQUE` (`entrenador_numero_cc` ASC)  ,
  CONSTRAINT `fk_rutinas_entrenador1`
    FOREIGN KEY (`entrenador_numero_cc`)
    REFERENCES `sportcode_`.`entrenador` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Jugador` (
  `ti` INT NOT NULL,
  `avances` TEXT NOT NULL,
  `entrenador_cc_id` INT NOT NULL,
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ti`),
  INDEX `fk_Jugador_entrenador_idx` (`entrenador_cc_id` ASC)  ,
  UNIQUE INDEX `entrenador_cc_id_UNIQUE` (`entrenador_cc_id` ASC)  ,
  INDEX `fk_Jugador_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_Jugador_entrenador`
    FOREIGN KEY (`entrenador_cc_id`)
    REFERENCES `sportcode_`.`entrenador` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Torneo` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Torneo` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `nombre_torneo` VARCHAR(45) NOT NULL,
  `nombre_cancha` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`resultados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`resultados` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`resultados` (
  `cod_de_partido` INT NOT NULL,
  `numero` TINYINT NULL,
  `PJ` TINYINT NULL,
  `G` TINYINT NULL,
  `E` TINYINT NULL,
  `P` TINYINT NULL,
  `CF` TINYINT NULL,
  `GC` TINYINT NULL,
  `DG` TINYINT NULL,
  `Pts` INT NULL,
  `Torneos_numero` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`cod_de_partido`),
  INDEX `fk_resultados_Torneos1_idx` (`Torneos_numero` ASC)  ,
  UNIQUE INDEX `Torneos_numero_UNIQUE` (`Torneos_numero` ASC)  ,
  CONSTRAINT `fk_resultados_Torneos1`
    FOREIGN KEY (`Torneos_numero`)
    REFERENCES `sportcode_`.`Torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Formato_inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Formato_inscripcion` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Formato_inscripcion` (
  `codigo` INT NOT NULL,
  `nombre_escuela` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`revision_medica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`revision_medica` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`revision_medica` (
  `codigo` INT NOT NULL,
  `tipo_de_sangre` VARCHAR(3) NOT NULL,
  `historia_clinica` TEXT NOT NULL,
  `Jugador_ti` INT NOT NULL,
  `Formato_inscripcion_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_revision_medica_Jugador1_idx` (`Jugador_ti` ASC)  ,
  INDEX `fk_revision_medica_Formato_inscripcion1_idx` (`Formato_inscripcion_codigo` ASC)  ,
  UNIQUE INDEX `Formato_inscripcion_codigo_UNIQUE` (`Formato_inscripcion_codigo` ASC)  ,
  UNIQUE INDEX `Jugador_ti_UNIQUE` (`Jugador_ti` ASC)  ,
  CONSTRAINT `fk_revision_medica_Jugador1`
    FOREIGN KEY (`Jugador_ti`)
    REFERENCES `sportcode_`.`Jugador` (`ti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revision_medica_Formato_inscripcion1`
    FOREIGN KEY (`Formato_inscripcion_codigo`)
    REFERENCES `sportcode_`.`Formato_inscripcion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

  
-- -----------------------------------------------------
-- Table `sportcode_`.`Acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Acudiente` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Acudiente` (
  `numero_cc` INT NOT NULL,
  `tipo_parentesco` VARCHAR(45) NOT NULL,
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`numero_cc`),
  INDEX `fk_Acudiente_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC) ,
  CONSTRAINT `fk_Acudiente_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Cotizacion` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Cotizacion` (
  `id` INT NOT NULL,
  `nombre_tienda` VARCHAR(45) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `Acudiente_numero_cc` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cotizacion_Acudiente1_idx` (`Acudiente_numero_cc` ASC)  ,
  UNIQUE INDEX `Acudiente_numero_cc_UNIQUE` (`Acudiente_numero_cc` ASC)  ,
  CONSTRAINT `fk_Cotizacion_Acudiente1`
    FOREIGN KEY (`Acudiente_numero_cc`)
    REFERENCES `sportcode_`.`Acudiente` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Orden_de_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Orden_de_compra` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Orden_de_compra` (
  `consecutivo` INT NOT NULL,
  `valor` INT NOT NULL,
  `Acudiente_numero_cc` INT NOT NULL,
  `Cotizacion_id` INT NOT NULL,
  PRIMARY KEY (`consecutivo`),
  INDEX `fk_Orden_de_compra_Acudiente1_idx` (`Acudiente_numero_cc` ASC)  ,
  UNIQUE INDEX `Acudiente_numero_cc_UNIQUE` (`Acudiente_numero_cc` ASC)  ,
  INDEX `fk_Orden_de_compra_Cotizacion1_idx` (`Cotizacion_id` ASC)  ,
  UNIQUE INDEX `Cotizacion_id_UNIQUE` (`Cotizacion_id` ASC)  ,
  CONSTRAINT `fk_Orden_de_compra_Acudiente1`
    FOREIGN KEY (`Acudiente_numero_cc`)
    REFERENCES `sportcode_`.`Acudiente` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_de_compra_Cotizacion1`
    FOREIGN KEY (`Cotizacion_id`)
    REFERENCES `sportcode_`.`Cotizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Inventario` (
  `id` INT NOT NULL,
  `tipo_producto` TEXT NOT NULL,
  `Administrador_numero_cc` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Inventario_Administrador1_idx` (`Administrador_numero_cc` ASC)  ,
  UNIQUE INDEX `Administrador_numero_cc_UNIQUE` (`Administrador_numero_cc` ASC)  ,
  CONSTRAINT `fk_Inventario_Administrador1`
    FOREIGN KEY (`Administrador_numero_cc`)
    REFERENCES `sportcode_`.`Administrador` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`cambiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`cambiar` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`cambiar` (
  `Inventario_id_inventario` INT NOT NULL,
  `Cotizacion_id_cotizacion` INT NOT NULL,
  PRIMARY KEY (`Inventario_id_inventario`, `Cotizacion_id_cotizacion`),
  INDEX `fk_Inventario_has_Cotizacion_Cotizacion1_idx` (`Cotizacion_id_cotizacion` ASC)  ,
  INDEX `fk_Inventario_has_Cotizacion_Inventario1_idx` (`Inventario_id_inventario` ASC),
  CONSTRAINT `fk_Inventario_has_Cotizacion_Inventario1`
    FOREIGN KEY (`Inventario_id_inventario`)
    REFERENCES `sportcode_`.`Inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_has_Cotizacion_Cotizacion1`
    FOREIGN KEY (`Cotizacion_id_cotizacion`)
    REFERENCES `sportcode_`.`Cotizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`calendario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`calendario` (
  `numero_calendario` INT NOT NULL,
  `horario_entrenamiento` DATETIME NULL,
  `Administrador_numero_cc` INT NOT NULL,
  `Torneos_numero` INT NOT NULL AUTO_INCREMENT,
  `Acudiente_numero_cc` 	INT NOT NULL,
  PRIMARY KEY (`numero_calendario`),
  INDEX `fk_calendario_Administrador1_idx` (`Administrador_numero_cc` ASC)  ,
  INDEX `fk_calendario_Torneos1_idx` (`Torneos_numero` ASC)  ,
  UNIQUE INDEX `Torneos_numero_UNIQUE` (`Torneos_numero` ASC)  ,
  UNIQUE INDEX `Administrador_numero_cc_UNIQUE` (`Administrador_numero_cc` ASC)  ,
  INDEX `fk_calendario_Acudiente1_idx` (`Acudiente_numero_cc` ASC)  ,
  UNIQUE INDEX `Acudiente_numero_cc_UNIQUE` (`Acudiente_numero_cc` ASC)  ,
  CONSTRAINT `fk_calendario_Administrador1`
    FOREIGN KEY (`Administrador_numero_cc`)
    REFERENCES `sportcode_`.`Administrador` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_Torneos1`
    FOREIGN KEY (`Torneos_numero`)
    REFERENCES `sportcode_`.`Torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_Acudiente1`
    FOREIGN KEY (`Acudiente_numero_cc`)
    REFERENCES `sportcode_`.`Acudiente` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`telefono_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`telefono_usuario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`telefono_usuario` (
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  `numero_telefono` INT NOT NULL,
  INDEX `fk_telefono_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_telefono_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`rol_usuario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`rol_usuario` (
  `Usuario_id` INT NOT NULL,
  `tipo_usuario` TINYINT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  INDEX `fk_e-mail_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_e-mail_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`producto_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`producto_inventario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`producto_inventario` (
  `Inventario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `cant_productos` TINYINT NOT NULL,
  INDEX `fk_producto_inventario_Inventario1_idx` (`Inventario_id` ASC)  ,
  PRIMARY KEY (`Inventario_id`),
  CONSTRAINT `fk_producto_inventario_Inventario1`
    FOREIGN KEY (`Inventario_id`)
    REFERENCES `sportcode_`.`Inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`posicion_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`posicion_jugador` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`posicion_jugador` (
  `Jugador_ti_jugador` INT NOT NULL,
  `posicion_campo` VARCHAR(45) NOT NULL,
  INDEX `fk_posicion_Jugador1_idx` (`Jugador_ti_jugador` ASC)  ,
  UNIQUE INDEX `Jugador_ti_jugador_UNIQUE` (`Jugador_ti_jugador` ASC)  ,
  CONSTRAINT `fk_posicion_Jugador1`
    FOREIGN KEY (`Jugador_ti_jugador`)
    REFERENCES `sportcode_`.`Jugador` (`ti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`telefono_inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`telefono_inscripcion` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`telefono_inscripcion` (
  `Formato_inscripcion_codigo` INT NOT NULL,
  `telefono` INT NOT NULL,
  INDEX `fk_table1_Formato_inscripcion1_idx` (`Formato_inscripcion_codigo` ASC)  ,
  UNIQUE INDEX `Formato_inscripcion_codigo_UNIQUE` (`Formato_inscripcion_codigo` ASC)  ,
  CONSTRAINT `fk_table1_Formato_inscripcion1`
    FOREIGN KEY (`Formato_inscripcion_codigo`)
    REFERENCES `sportcode_`.`Formato_inscripcion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`enfermedades_r_medica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`enfermedades_r_medica` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`enfermedades_r_medica` (
  `revision_medica_codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `causas` TEXT NULL,
  `tratamiento` TEXT NULL,
  INDEX `fk_enfermedades_r_medica_revision_medica1_idx` (`revision_medica_codigo` ASC)  ,
  UNIQUE INDEX `revision_medica_serial_rev_med_UNIQUE` (`revision_medica_codigo` ASC)  ,
  CONSTRAINT `fk_enfermedades_r_medica_revision_medica1`
    FOREIGN KEY (`revision_medica_codigo`)
    REFERENCES `sportcode_`.`revision_medica` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`Medidas_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`Medidas_jugador` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`Medidas_jugador` (
  `Jugador_ti` INT NOT NULL,
  `medida_pantaloneta` VARCHAR(2) NULL,
  `medida_camiseta` VARCHAR(45) NULL,
  `medida_zapatillas` VARCHAR(45) NULL,
  INDEX `fk_Progreso_jugador_Jugador1_idx` (`Jugador_ti` ASC)  ,
  UNIQUE INDEX `Jugador_ti_UNIQUE` (`Jugador_ti` ASC)  ,
  CONSTRAINT `fk_Progreso_jugador_Jugador1`
    FOREIGN KEY (`Jugador_ti`)
    REFERENCES `sportcode_`.`Jugador` (`ti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`email_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`email_usuario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`email_usuario` (
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  `direccion_email` VARCHAR(45) NOT NULL,
  INDEX `fk_e-mail_usuario_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_e-mail_usuario_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`fecha_f_inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`fecha_f_inscripcion` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`fecha_f_inscripcion` (
  `Formato_inscripcion_codigo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  INDEX `fk_fecha_f_inscripcion_Formato_inscripcion1_idx` (`Formato_inscripcion_codigo` ASC)  ,
  UNIQUE INDEX `Formato_inscripcion_codigo_UNIQUE` (`Formato_inscripcion_codigo` ASC)  ,
  CONSTRAINT `fk_fecha_f_inscripcion_Formato_inscripcion1`
    FOREIGN KEY (`Formato_inscripcion_codigo`)
    REFERENCES `sportcode_`.`Formato_inscripcion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`fecha_o_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`fecha_o_compra` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`fecha_o_compra` (
  `Orden_de_compra_consecutivo` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  INDEX `fk_fecha_o_compra_Orden_de_compra1_idx` (`Orden_de_compra_consecutivo` ASC)  ,
  UNIQUE INDEX `Orden_de_compra_consecutivo_UNIQUE` (`Orden_de_compra_consecutivo` ASC)  ,
  CONSTRAINT `fk_fecha_o_compra_Orden_de_compra1`
    FOREIGN KEY (`Orden_de_compra_consecutivo`)
    REFERENCES `sportcode_`.`Orden_de_compra` (`consecutivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`edad_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`edad_usuario` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`edad_usuario` (
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATE NOT NULL,
  INDEX `fk_edad_usuario_Usuario1_idx` (`Usuario_id` ASC)  ,
  UNIQUE INDEX `Usuario_id_UNIQUE` (`Usuario_id` ASC)  ,
  CONSTRAINT `fk_edad_usuario_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sportcode_`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`torneo_fecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`torneo_fecha` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`torneo_fecha` (
  `Torneos_numero` INT NOT NULL,
  `fecha_torneo` VARCHAR(45) NULL,
  `hora_torneo` VARCHAR(45) NULL,
  INDEX `fk_torneo_fecha_Torneos1_idx` (`Torneos_numero` ASC)  ,
  UNIQUE INDEX `Torneos_numero_UNIQUE` (`Torneos_numero` ASC)  ,
  CONSTRAINT `fk_torneo_fecha_Torneos1`
    FOREIGN KEY (`Torneos_numero`)
    REFERENCES `sportcode_`.`Torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportcode`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportcode_`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `sportcode_`.`comentarios` (
  `Acudiente_numero_cc` INT NOT NULL,
  `primero_nombre` VARCHAR(45) NOT NULL,
  `primero_apellido` VARCHAR(45) NOT NULL,
  `texto` TEXT NOT NULL,
  `respuesta` TEXT NULL,
  INDEX `fk_comentarios_Acudiente1_idx` (`Acudiente_numero_cc` ASC)  ,
  UNIQUE INDEX `Acudiente_numero_cc_UNIQUE` (`Acudiente_numero_cc` ASC)  ,
  CONSTRAINT `fk_comentarios_Acudiente1`
    FOREIGN KEY (`Acudiente_numero_cc`)
    REFERENCES `sportcode_`.`Acudiente` (`numero_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
