-- MySQL Script generated by MySQL Workbench
-- Sun Aug 15 02:38:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sc` ;

-- -----------------------------------------------------
-- Schema sc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sc` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `sc`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `primero_nombre` VARCHAR(45) NULL,
  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `primero_apellido` VARCHAR(45) NULL,
  `segundo_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_Identificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Identificacion` (
  `usuario_id` INT(11) NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NULL,
  `numero_id` VARCHAR(45) NULL,
  `edad` INT(2) NULL,
  INDEX `fk_table1_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_rol_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_rol_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` INT(1) NOT NULL DEFAULT 4,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sc`.`tbl_calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_calendario` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_calendario` (
  `numero_calendario` INT(11) NOT NULL,
  `descripcion_evento` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`numero_calendario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_rutinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_rutinas` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_rutinas` (
  `numero` INT(11) NOT NULL,
  `velocidad` VARCHAR(45) NULL DEFAULT NULL,
  `resistencia` VARCHAR(45) NULL DEFAULT NULL,
  `fuerza` VARCHAR(45) NULL DEFAULT NULL,
  `coordinacion` VARCHAR(45) NULL DEFAULT NULL,
  `entrenador_numero_cc` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `calendario_numero` INT(11) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_rutinas_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_rutinas_calendario1_idx` (`calendario_numero` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rutinas_calendario1`
    FOREIGN KEY (`calendario_numero`)
    REFERENCES `sc`.`tbl_calendario` (`numero_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_jugador` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_jugador` (
  `id` VARCHAR(45) NOT NULL,
  `tipo_jugador` VARCHAR(45) NULL,
  `posicion_campo` VARCHAR(45) NULL DEFAULT NULL,
  `num_jugador_campo` INT(2) NULL,
  `categoria_jugador` VARCHAR(45) NULL,
  `rutinas_numero` INT(11) NOT NULL,
  `usuario_id` INT(11) NULL,
  INDEX `fk_jugador_rutinas1_idx` (`rutinas_numero` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_jugador_rutinas1`
    FOREIGN KEY (`rutinas_numero`)
    REFERENCES `sc`.`tbl_rutinas` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_revision_mental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_revision_mental` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_revision_mental` (
  `jugador_usuario_id` INT(11) NOT NULL,
  `cualidades` VARCHAR(45) NULL,
  `habilidad_psiquicas` VARCHAR(45) NULL,
  `debilidades_psiquicas` VARCHAR(45) NULL,
  `habilidad_psicomotriz` VARCHAR(45) NULL,
  CONSTRAINT `fk_revision_mental_jugador1`
    FOREIGN KEY (`jugador_usuario_id`)
    REFERENCES `sc`.`tbl_jugador` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_inventario` (
  `oc_id` INT NOT NULL,
  `inventario` VARCHAR(45) NULL,
  `lugar_estant` VARCHAR(255) NULL,
  `telefono` INT(11) NULL,
  PRIMARY KEY (`oc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_factura` (
  `id` INT NOT NULL,
  `fk_acudiente` INT(11) NULL,
  `fk_admin` INT(11) NULL,
  `fecha` DATE NULL,
  `total_productos` INT(11) NULL,
  `valor_total` DOUBLE NULL,
  `impuestos` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_usuario1_idx` (`fk_acudiente` ASC) VISIBLE,
  INDEX `fk_factura_usuario2_idx` (`fk_admin` ASC) VISIBLE,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`fk_acudiente`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario2`
    FOREIGN KEY (`fk_admin`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_categoria_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_categoria_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_categoria_producto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_producto` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `valor_venta` VARCHAR(45) NULL,
  `categoria_producto_id` INT NULL,
  `pto_total` VARCHAR(45) NULL,
  INDEX `fk_producto_categoria_producto1_idx` (`categoria_producto_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_categoria_producto1`
    FOREIGN KEY (`categoria_producto_id`)
    REFERENCES `mydb`.`tbl_categoria_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_factura_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_factura_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_factura_producto` (
  `id` VARCHAR(45) NOT NULL,
  `factura_id` INT NULL,
  `producto_id` VARCHAR(45) NULL,
  `valor_unidad` DOUBLE NULL,
  `cantidad` INT(11) NULL,
  INDEX `fk_factura_producto_factura1_idx` (`factura_id` ASC) VISIBLE,
  INDEX `fk_factura_producto_producto1_idx` (`producto_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_factura_producto_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `mydb`.`tbl_factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`tbl_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sc` ;

-- -----------------------------------------------------
-- Table `sc`.`tbl_comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_comentarios` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_comentarios` (
  `cmnt_id` INT NOT NULL,
  `cmnt_texto` VARCHAR(245) NULL,
  `cmnt_fecha` DATE NULL,
  PRIMARY KEY (`cmnt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_orden_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_orden_compra` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_orden_compra` (
  `id` INT(11) NOT NULL,
  `num_venta` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `novedad` VARCHAR(255) NULL,
  `calendario_numero` INT(11) NULL,
  `usuario_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cotizacion_calendario1_idx` (`calendario_numero` ASC) VISIBLE,
  INDEX `fk_orden_compra_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cotizacion_calendario1`
    FOREIGN KEY (`calendario_numero`)
    REFERENCES `sc`.`tbl_calendario` (`numero_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_compra_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_enfermedades_medicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_enfermedades_medicas` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_enfermedades_medicas` (
  `jugador_usuario_id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `causas` VARCHAR(245) NULL DEFAULT NULL,
  `tratamiento` VARCHAR(245) NULL DEFAULT NULL,
  `tipo_de_sangre` VARCHAR(45) NULL,
  `historial_clinico` VARCHAR(45) NULL,
  CONSTRAINT `fk_enfermedades_r_medica_jugador1`
    FOREIGN KEY (`jugador_usuario_id`)
    REFERENCES `sc`.`tbl_jugador` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_medidas_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_medidas_jugador` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_medidas_jugador` (
  `jugador_usuario_id` INT(11) NOT NULL,
  `medida_pantaloneta` VARCHAR(2) NULL DEFAULT NULL,
  `medida_camiseta` VARCHAR(45) NULL DEFAULT NULL,
  `medida_zapatillas` VARCHAR(45) NULL DEFAULT NULL,
  CONSTRAINT `fk_medidas_jugador_jugador1`
    FOREIGN KEY (`jugador_usuario_id`)
    REFERENCES `sc`.`tbl_jugador` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_oc_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_oc_producto` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_oc_producto` (
  `id` VARCHAR(45) NOT NULL,
  `cantidad` INT(11) NULL,
  `valor_venta` DOUBLE NULL DEFAULT NULL,
  `usuario_id` INT(11) NULL,
  `orden_compra_id` INT(11) NULL,
  `orden_compra_id1` INT(11) NULL,
  `producto_id` VARCHAR(45) NULL,
  INDEX `fk_oc_producto_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_oc_producto_orden_compra1_idx` (`orden_compra_id1` ASC) VISIBLE,
  INDEX `fk_oc_producto_producto1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_oc_producto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oc_producto_inventario1`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `mydb`.`tbl_inventario` (`oc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oc_producto_orden_compra1`
    FOREIGN KEY (`orden_compra_id1`)
    REFERENCES `sc`.`tbl_orden_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oc_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`tbl_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_torneo` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_torneo` (
  `numero` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_torneo` VARCHAR(45) NOT NULL,
  `nombre_cancha` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`resultados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`resultados` ;

CREATE TABLE IF NOT EXISTS `sc`.`resultados` (
  `Torneos_numero` INT(11) NULL AUTO_INCREMENT,
  `PJ` INT(4) NULL DEFAULT NULL,
  `G` INT(4) NULL DEFAULT NULL,
  `E` INT(4) NULL DEFAULT NULL,
  `P` INT(4) NULL DEFAULT NULL,
  `CF` INT(4) NULL DEFAULT NULL,
  `GC` INT(4) NULL DEFAULT NULL,
  `DG` INT(4) NULL DEFAULT NULL,
  `Pts` INT(11) NULL DEFAULT NULL,
  INDEX `fk_resultados_Torneos1_idx` (`Torneos_numero` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_Torneos1`
    FOREIGN KEY (`Torneos_numero`)
    REFERENCES `sc`.`tbl_torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_revision_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_revision_fisica` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_revision_fisica` (
  `jugador_usuario_id` INT(11) NOT NULL,
  `estatura` INT GENERATED ALWAYS AS () VIRTUAL,
  `peso` INT NULL,
  `genero` VARCHAR(45) NULL,
  INDEX `fk_revision_medica_jugador1_idx` (`jugador_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_revision_medica_jugador1`
    FOREIGN KEY (`jugador_usuario_id`)
    REFERENCES `sc`.`tbl_jugador` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_telefono_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_telefono_usuario` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_telefono_usuario` (
  `Usuario_id` INT(11) NULL AUTO_INCREMENT,
  `numero_telefono` INT(11) NULL,
  INDEX `fk_telefono_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `numero_telefono_UNIQUE` (`numero_telefono` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_tiene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_tiene` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_tiene` (
  `usuario_id` INT(11) NULL,
  `rol_usuario_id` INT NULL,
  INDEX `fk_usuario_has_rol_usuario_rol_usuario1_idx` (`rol_usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_rol_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_rol_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_usuario_rol_usuario1`
    FOREIGN KEY (`rol_usuario_id`)
    REFERENCES `mydb`.`tbl_rol_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_gestionar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_gestionar` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_gestionar` (
  `torneo_numero` INT(11) NULL,
  `usuario_id` INT(11) NULL,
  INDEX `fk_torneo_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_torneo_has_usuario_torneo1_idx` (`torneo_numero` ASC) VISIBLE,
  CONSTRAINT `fk_torneo_has_usuario_torneo1`
    FOREIGN KEY (`torneo_numero`)
    REFERENCES `sc`.`tbl_torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_generar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_generar` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_generar` (
  `calendario_numero` INT(11) NULL,
  `usuario_id` INT(11) NULL,
  INDEX `fk_calendario_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_calendario_has_usuario_calendario1_idx` (`calendario_numero` ASC) VISIBLE,
  CONSTRAINT `fk_calendario_has_usuario_calendario1`
    FOREIGN KEY (`calendario_numero`)
    REFERENCES `sc`.`tbl_calendario` (`numero_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_adquirir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_adquirir` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_adquirir` (
  `torneo_numero` INT(11) NULL,
  `calendario_numero` INT(11) NULL,
  INDEX `fk_torneo_has_calendario_calendario1_idx` (`calendario_numero` ASC) VISIBLE,
  INDEX `fk_torneo_has_calendario_torneo1_idx` (`torneo_numero` ASC) VISIBLE,
  CONSTRAINT `fk_torneo_has_calendario_torneo1`
    FOREIGN KEY (`torneo_numero`)
    REFERENCES `sc`.`tbl_torneo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_has_calendario_calendario1`
    FOREIGN KEY (`calendario_numero`)
    REFERENCES `sc`.`tbl_calendario` (`numero_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sc`.`tbl_hacer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sc`.`tbl_hacer` ;

CREATE TABLE IF NOT EXISTS `sc`.`tbl_hacer` (
  `usuario_id` INT(11) NULL,
  `cmnt_id` INT NULL,
  INDEX `fk_usuario_has_comentarios_comentarios1_idx` (`cmnt_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_comentarios_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_comentarios_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sc`.`tbl_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_comentarios_comentarios1`
    FOREIGN KEY (`cmnt_id`)
    REFERENCES `sc`.`tbl_comentarios` (`cmnt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
