-- MySQL Script generated by MySQL Workbench
-- Sat May 29 12:15:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tallerIV
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tallerIV` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallerIV` DEFAULT CHARACTER SET utf8 ;
USE `tallerIV` ;

-- -----------------------------------------------------
-- Table `tallerIV`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallerIV`.`persona` ;

CREATE TABLE IF NOT EXISTS `tallerIV`.`persona` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `sexo` CHAR NULL,
  `fechaNacimiento` DATETIME NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerIV`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallerIV`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tallerIV`.`usuario` (
  `persona_codigo` INT NOT NULL,
  `usuario` VARCHAR(20) NULL,
  `clave` VARCHAR(45) NULL,
  `tipo` CHAR NULL,
  `estado` TINYINT NULL,
  INDEX `fk_usuario_persona_idx` (`persona_codigo` ASC) ,
  UNIQUE INDEX `persona_codigo_UNIQUE` (`persona_codigo` ASC) ,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_codigo`)
    REFERENCES `tallerIV`.`persona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerIV`.`telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallerIV`.`telefono` ;

CREATE TABLE IF NOT EXISTS `tallerIV`.`telefono` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `numero` CHAR(9) NULL,
  `persona_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_telefono_persona1_idx` (`persona_codigo` ASC) ,
  UNIQUE INDEX `persona_codigo_UNIQUE` (`persona_codigo` ASC) ,
  CONSTRAINT `fk_telefono_persona1`
    FOREIGN KEY (`persona_codigo`)
    REFERENCES `tallerIV`.`persona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerIV`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallerIV`.`categoria` ;

CREATE TABLE IF NOT EXISTS `tallerIV`.`categoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerIV`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallerIV`.`nota` ;

CREATE TABLE IF NOT EXISTS `tallerIV`.`nota` (
  `categoria_codigo` INT NOT NULL,
  `persona_codigo` INT NOT NULL,
  `encabezado` VARCHAR(45) NULL,
  `cuerpo` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `comentarioAdmin` VARCHAR(50) NOT NULL,
  `valorizacion` TINYINT NOT NULL,
  INDEX `fk_nota_categoria1_idx` (`categoria_codigo` ASC) ,
  INDEX `fk_nota_persona1_idx` (`persona_codigo` ASC) ,
  UNIQUE INDEX `encabezado_UNIQUE` (`encabezado` ASC) ,
  UNIQUE INDEX `persona_codigo_UNIQUE` (`persona_codigo` ASC) ,
  CONSTRAINT `fk_nota_categoria1`
    FOREIGN KEY (`categoria_codigo`)
    REFERENCES `tallerIV`.`categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_persona1`
    FOREIGN KEY (`persona_codigo`)
    REFERENCES `tallerIV`.`persona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
